---
source: tests/snapshots.rs
assertion_line: 54
expression: output
---
success = false
stdout = ''
stderr = '''
Error:   × type mismatch
   ╭─[lambda_inference.rice:2:5]
 1 │ fn apply_twice(f: _, x: _) -> _ {
 2 │     f(f(x))
   ·     ┬
   ·     ╰── expected function, found `?0`
 3 │ }
   ╰────

'''
